'''
@auther: Samaneh

This module reads the cluster file generated by CD-HIT software and extract sequences'
names of the clusters into a text file 

'''
from Bio import SeqIO
import pandas as pd
import numpy as np
import xlsxwriter
import re

##################################################################################

def extraction(clusterFile):

	sepFile = open("/home/samaneh/AHRD/clustering/clusters.txt","w")
	clstr = clusterFile.readlines()
	temprow = 0
	clstrNumber = "Null"
	seqIdList = []

	for line in file:
		if ">Cluster" in line:
			if clstrNumber != "Null":
				seqIdDict[clstrNumber]=seqIdList
				l = len(seqIdList)

				for i in range (0,l):
					sepFile.write(seqIdList[i])
					sepFile.write(" ")
				sepFile.write("\n")
				seqIdList = [] 
			clstrNumber = re.sub("\>[A-Za-z]*\s","",line) 

		if ">sp|" in line:
			line = re.sub(".*>sp\|","",line)
			seqId = re.sub("\|.*","",line)
			seqId = seqId.strip("\n")
			seqIdList.append(seqId)	

def main():
	clstrFile = open("/home/samaneh/AHRD/clustering/uniprot_sprot_clusterd.clstr","r")
	extraction(clstrFile)

if __name__ == "__main__": 		
	main()	




